language: android

sudo: required

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-google-m2repository
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - '.+'

jdk:
  - oraclejdk8

before_install:
  - echo y | sudo apt-get update
  - echo y | sudo apt-get install openjdk-6-jre
  - export JAVA6_HOME=/usr/lib/jvm/java-6-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
  - chmod +x gradlew

script:
  - ./gradlew build